### ISSUE TITLE
Memory Map Overlay looks weird in Sepia Mode

### ISSUE THREAD

**Issue by RotterdamIsHardAsHell** [v3rv41n/NeoDaysPlus#5]
![neo+](https://user-images.githubusercontent.com/74435632/134713632-54eb3fa1-00ec-4118-9e3e-cda6ddb6cb35.png)
![neo](https://user-images.githubusercontent.com/74435632/134713636-22973fb6-09fb-45db-a753-fb162c81b928.png)
 I'm not sure if the sepia background tiles are meant to be like this or if this is an issue... 

Anyway, love the new additions :)

**Comment by v3rv41n** [comment]
Sepia mode tints all the colours in the tiles. Since NDP has a background colour on terrain tiles, that background colour would be tinted in a similar way to the objects.

That being said, apart from the brighter view, I can see a few tiles that have a black square around them. This is because those tiles have a transparent background (since they are 'active' tiles) that go over others. That can be remedied by giving those a background colour as well, BUT in the upcoming version 1.8.0 (still in dev but close to being done), I've updated A LOT of the vehicle tiles to looks more like a vehicle, but also take up a bit more tile real estate and have their own background colours! 

So hopefully in the 1.8.0 version, the vehicles in the memory map in sepia mode wont show those black squares and flow a bit better.

Thanks for your continued support and bringing this to my attention, should be looking smooth shortly!

**Comment by v3rv41n** [comment]
Also thanks for those screenshots, I'll be adding some background colour to the boulder as well since I see a black square around it too
